<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>TS-TP4</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>d1e9a5ee-9360-4c61-a821-e62cf9590779</testSuiteGuid>
   <testCaseLink>
      <guid>b1a5a453-879c-498f-90c8-86c92dd15f7c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TYCS/SauceDemo/TC-SD-LoginValido</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>57678689-e7ca-4255-9e43-b7d550d28c92</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cf06e1c4-a9a3-4d6a-b2f5-5cd075950cfb</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>88570770-ac40-4d48-9bfc-706c75894265</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TYCS/SauceDemo/TC-SD-LoginMsError</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c50844c6-0326-4f86-ba12-455bc1dbed73</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3c69a404-87d5-45e1-b8fa-893cb3c422e7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>31b19e94-974a-4991-af8b-149e9581c51a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>725e5243-4e21-486a-9b39-52333efe2e1c</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>f8ce9719-a6b8-4931-a330-df2e0a40857c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TYCS/SauceDemo/TC-SD-LoginMsVacioUS</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ad7dea73-fc6d-43bd-9a5a-f81ca7bde851</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4d137dd7-7258-4ad4-acf5-86894fc341ba</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>434dcfbd-8f47-4c86-b79f-5b225b8b20c0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f6176200-c9cf-4e10-91ee-779085c6030a</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>ae55dc9e-93e4-44fa-afd5-9cfff9b39fc5</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TYCS/SauceDemo/TC-SD-LoginMsVacioPW</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>066c3057-2a66-4ac6-b3ba-2ea6a3aded4b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bafaeff7-9b0b-4c4e-9973-a00e515ea3eb</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c0508f9a-fe37-49f4-a12f-65c877b2f350</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f3b547c3-fad9-4004-9958-b372095ec0d1</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>a1ac78d0-2e1e-43d0-95a3-f41095c42a82</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TYCS/SauceDemo/TC-SD-LoginValidoDF</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>4d789358-0181-45dc-99e8-e19698950a72</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/DF_SauceDemo_Valid</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>4d789358-0181-45dc-99e8-e19698950a72</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>USUARIO</value>
         <variableId>87853eb1-826b-4ef2-9d1e-0911cc4a9c15</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>4d789358-0181-45dc-99e8-e19698950a72</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>CONTASEÑA</value>
         <variableId>d400b689-d340-4981-be83-368d4efcb013</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d837b056-1302-4a28-b6e5-b780795d1f8b</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>d8d1afea-8d15-433f-91f5-7711ee9e0e8a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TYCS/SauceDemo/TC-SD-LoginInvalidoDF</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>44772fa9-e529-41c3-bc24-991d34be53d3</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/DF_SauceDemo_Invalid</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>44772fa9-e529-41c3-bc24-991d34be53d3</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>USUARIO</value>
         <variableId>5c494917-16d9-4e73-8fe7-c1928c22b4c7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>44772fa9-e529-41c3-bc24-991d34be53d3</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>CONTRASEÑA</value>
         <variableId>e0f91d8d-3650-4974-b8cc-518ae9570c0f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>44772fa9-e529-41c3-bc24-991d34be53d3</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>MENSAJE</value>
         <variableId>81e8a138-2939-4ad3-9ed9-d49496002571</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>44772fa9-e529-41c3-bc24-991d34be53d3</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>ARCHIVO</value>
         <variableId>31c43609-65f6-43b4-91f2-2072d1c76644</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
